apiVersion: v1
kind: Service
metadata:
  name: new-service-checker
  namespace: monitoring
spec:
  selector:
    app: new-service-checker
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
