apiVersion: v1
kind: Service
metadata:
  name: new-service-checker-metrics
  namespace: monitoring
spec:
  selector:
    app: new-service-checker
  ports:
    - name: http
      port: 8000
      targetPort: 8000
